---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "ofddb"
  namespace: "default"
  labels:
    app: "ofddb"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "ofddb"
  template:
    metadata:
      labels:
        app: "ofddb"
    spec:
      containers:
      - name: "ofddatabase-sha256-1"
        image: "gcr.io/charged-ground-326209/github.com/jyothsnapandrala/ofddatabase@sha256:3498ac9126975cac5bd3e2dbd9ab99ad303397704846365c0dd52243924b7cce"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "ofddb-hpa-d6jo"
  namespace: "default"
  labels:
    app: "ofddb"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "ofddb"
    apiVersion: "apps/v1"
  minReplicas: 1
maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
